// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package dependency

import (
	"context"
	"github.com/google/wire"
	"go-hexagonal/adapter/repository/mysql/entity"
	"go-hexagonal/domain/event"
	"go-hexagonal/domain/repo"
	"go-hexagonal/domain/service"
)

// Injectors from wire.go:

// InitializeServices initializes all services
func InitializeServices(ctx context.Context) (*service.Services, error) {
	// Create repositories
	entityExample := entity.NewExample()

	// Create event bus and handlers
	inMemoryEventBus := event.NewInMemoryEventBus()
	loggingHandler := event.NewLoggingEventHandler()
	exampleHandler := event.NewExampleEventHandler()

	// Register event handlers
	inMemoryEventBus.Subscribe(loggingHandler)
	inMemoryEventBus.Subscribe(exampleHandler)

	// Create services
	exampleService := service.NewExampleService(ctx)
	exampleService.Repository = entityExample
	exampleService.EventBus = inMemoryEventBus

	// Create services container
	services := service.NewServices(exampleService, inMemoryEventBus)

	return services, nil
}

// Injected is an alias for InitializeServices for backward compatibility
func Injected(ctx context.Context) (*service.Services, error) {
	return InitializeServices(ctx)
}

// wire.go:

// RepositorySet defines repository dependencies
var RepositorySet = wire.NewSet(entity.NewExample, wire.Bind(new(repo.IExampleRepo), new(*entity.EntityExample)))

// EventSet defines event-related dependencies
var EventSet = wire.NewSet(event.NewInMemoryEventBus, wire.Bind(new(event.EventBus), new(*event.InMemoryEventBus)), event.NewLoggingEventHandler, event.NewExampleEventHandler)

// ServiceSet defines service dependencies
var ServiceSet = wire.NewSet(service.NewExampleService)

// ApplicationSet defines application layer dependencies
var ApplicationSet = wire.NewSet()

// AllSets combines all dependency sets
var AllSets = wire.NewSet(
	RepositorySet,
	EventSet,
	ServiceSet,
	ApplicationSet,
)

// provideServices creates a Services instance with all dependencies
func provideServices(exampleService *service.ExampleService, eventBus event.EventBus) *service.Services {
	return service.NewServices(exampleService, eventBus)
}
